### ISSUE TITLE
Image not found

### ISSUE THREAD

**Issue by zhanghai** [futurenda/docker-android-sdk#1]
See https://circleci.com/gh/futurenda/android/224 .

**Comment by zenozeng** [comment]
- https://hub.docker.com/r/futurenda/android-sdk/builds/
- https://hub.docker.com/r/futurenda/android-sdk/builds/btjv4ropfjduuvhe36pwzvy/

Build 失败了

**Comment by zhanghai** [comment]
我只 bump 了版本号……

**Comment by zenozeng** [comment]
@DreaminginCodeZH 因为 debian 上游那个包不见了。噗。我现在在 apt get 的时候加了 `-t jessie-backports`，应该好了，还在 build 中。一会改好了再 at 你一下.

**Comment by zenozeng** [comment]
https://circleci.com/gh/futurenda/android/226
